#!/usr/bin/env bash

# Automatic renew the HTTPS by let's encrypt.

if [[ ! -d /usr/local/srs-terraform && $(uname -s) == 'Darwin' ]]; then
  echo "Directly finish renew for macOS development"
  sleep 3; exit 0;
fi

LIVE_DOMAINS=$(ls -d /etc/letsencrypt/live/*/ |wc -l)
if [[ $LIVE_DOMAINS -eq 0 ]]; then echo "No domains in /etc/letsencrypt/live/"; exit 0; fi

# See https://github.com/ossrs/srs/issues/2864#issuecomment-1027944527
certbot renew --post-hook 'systemctl reload nginx.service'

