#!/usr/bin/env bash

# Execute by: bash xxx.sh or bash zzz/yyy/xxx.sh or ./xxx.sh or ./zzz/yyy/xxx.sh source xxx.sh
REALPATH=$(realpath ${BASH_SOURCE[0]})
SCRIPT_DIR=$(cd $(dirname ${REALPATH}) && pwd)
WORK_DIR=$(cd $(dirname ${REALPATH}) && pwd)
echo "BASH_SOURCE=${BASH_SOURCE}, REALPATH=${REALPATH}, SCRIPT_DIR=${SCRIPT_DIR}, WORK_DIR=${WORK_DIR}"
cd ${WORK_DIR}

APP_ARGS=$@
echo "Run srs-cloud with args: ${APP_ARGS}, WORK_DIR:${WORK_DIR}"

# Get the metadata of machine.
if [[ -f ${WORK_DIR}/.env ]]; then source ${WORK_DIR}/.env; fi
echo "LoadEnv CLOUD=$CLOUD REGION=$REGION, SOURCE=$SOURCE"

# Setup the platform.
bash auto/setup

# Start redis.
bash auto/start_redis

# Start SRS.
bash auto/start_srs

# Start the application server.
./platform $APP_ARGS

# Stop redis.
bash auto/stop_redis

# Stop SRS.
bash auto/stop_srs
