#!/usr/bin/env bash

# Execute by: bash xxx.sh or bash zzz/yyy/xxx.sh or ./xxx.sh or ./zzz/yyy/xxx.sh source xxx.sh
REALPATH=$(realpath ${BASH_SOURCE[0]})
SCRIPT_DIR=$(cd $(dirname ${REALPATH}) && pwd)
WORK_DIR=$(cd $(dirname ${REALPATH})/.. && pwd)
echo "BASH_SOURCE=${BASH_SOURCE}, REALPATH=${REALPATH}, SCRIPT_DIR=${SCRIPT_DIR}, WORK_DIR=${WORK_DIR}"
cd ${WORK_DIR}

echo "Start SRS server, WORK_DIR:${WORK_DIR}"

# Get the metadata of machine.
if [[ -f ${WORK_DIR}/.env ]]; then source ${WORK_DIR}/.env; fi
echo "LoadEnv CLOUD=$CLOUD REGION=$REGION, SOURCE=$SOURCE"

if [[ -d /usr/local/srs ]]; then
  SRS_PARAMS="-c /usr/local/srs/conf/lighthouse.conf"
  echo "Run srs-server $SRS_PARAMS"

  # Current directory should be /usr/local/srs-cloud/platform
  /usr/local/srs/objs/srs $SRS_PARAMS &&
  SRS_PID_FILE="./objs/srs.pid"
  if [[ $? -ne 0 ]]; then echo "Start SRS failed"; exit 1; fi

  for ((i=0; i<10; i++)); do
    if [[ -f $SRS_PID_FILE ]]; then
      ps -p `cat $SRS_PID_FILE` 1>/dev/null 2>/dev/null &&
      echo "SRS server started, pid=`cat $SRS_PID_FILE`" &&
      break
    fi
    sleep 0.3
  done

  ps -p `cat $SRS_PID_FILE` 1>/dev/null 2>/dev/null
  if [[ $? -ne 0 ]]; then echo "Check SRS failed"; exit 1; fi
fi

