#!/usr/bin/env bash

REALPATH=$(realpath $0)
WORK_DIR=$(cd $(dirname $REALPATH) && pwd)
echo "Start SRS server at $WORK_DIR from $0"

# Do everything at the same work directory.
cd $WORK_DIR/..

echo "Stop SRS server"

SRS_PID_FILE="./objs/srs.pid"
if [[ -f $SRS_PID_FILE ]]; then
  SRS_PID=`cat $SRS_PID_FILE`
  echo "Stopping SRS, pid=$SRS_PID"
  kill $SRS_PID 1>/dev/null 2>/dev/null

  # See https://stackoverflow.com/a/41613532/17679565
  timeout 10 tail --pid=$SRS_PID -f /dev/null
  echo "Stopped SRS, pid=$SRS_PID"
fi

