#!/usr/bin/env bash

echo "Foreach run script"

# Do not use swap, for some OS it fails.
if [[ -f /swapfile ]]; then
  swapoff /swapfile; rm -f /swapfile; echo "Remove /swapfile"
fi

# Generate coredump, see https://stackoverflow.com/a/47694315/17679565
if [[ -f /proc/sys/kernel/core_pattern && ! -d /cores ]]; then
  echo '/cores/core.%e.%p' | tee /proc/sys/kernel/core_pattern &&
  mkdir -p /cores && echo "Create dirs for coredump"
  if [[ $? -ne 0 ]]; then echo "Create dirs failed"; exit 1; fi
fi

# Revert the redis config, after migrate to docker.
# Also setup the redis password, so we must keep running this script.
bash auto/setup_redis
if [[ $? -ne 0 ]]; then echo "Setup redis failed"; exit 1; fi

# We setup the docker network.
bash auto/setup_network
if [[ $? -ne 0 ]]; then echo "Setup docker network failed"; exit 1; fi

# Target version in version.go
bash auto/switch_mgmt_version
if [[ $? -ne 0 ]]; then echo "Switch MGMT failed"; exit 1; fi

