#!/usr/bin/env bash

echo "Foreach run script"

# Initialize global configuration.
bash auto/init_global

# Revert the redis config, after migrate to docker.
# Also setup the redis password, so we must keep running this script.
bash auto/setup_redis
if [[ $? -ne 0 ]]; then echo "Setup redis failed"; exit 1; fi

# We setup the docker network.
bash auto/setup_network
if [[ $? -ne 0 ]]; then echo "Setup docker network failed"; exit 1; fi

