#!/usr/bin/env bash

echo "Foreach run script"

# Do not use swap, for some OS it fails.
if [[ -f /swapfile ]]; then
  swapoff /swapfile; rm -f /swapfile; echo "Remove /swapfile"
fi

# Do not use redis container, we run redis in platform now.
docker rm -f redis 2>/dev/null; echo "Remove redis container"

# Do not use SRS container, we run SRS in platform now.
docker rm -f srs-server 2>/dev/null; echo "Remove SRS container"

# Migrate .env to containers/data/config
if [[ ! -f containers/data/config/.env ]]; then
  touch .env && mkdir -p containers/data/config &&
  mv .env containers/data/config/.env &&
  ln -sf containers/data/config/.env .env &&
  echo "Migrate .env to containers/data/config/.env"
fi

# Generate coredump, see https://stackoverflow.com/a/47694315/17679565
if [[ -f /proc/sys/kernel/core_pattern && ! -d /cores ]]; then
  echo '/cores/core.%e.%p' | tee /proc/sys/kernel/core_pattern &&
  mkdir -p /cores && echo "Create dirs for coredump"
  if [[ $? -ne 0 ]]; then echo "Create dirs failed"; exit 1; fi
fi

# Revert the redis config, after migrate to docker.
# Also setup the redis password, so we must keep running this script.
bash auto/setup_redis
if [[ $? -ne 0 ]]; then echo "Setup redis failed"; exit 1; fi

# We setup the docker network.
bash auto/setup_network
if [[ $? -ne 0 ]]; then echo "Setup docker network failed"; exit 1; fi

