#!/usr/bin/env bash

# For CentOS 7, it's /etc/redis.conf
# For Ubuntu 20, it's /etc/redis/redis.conf
REDIS_CONF=/etc/redis.conf
if [[ ! -f $REDIS_CONF ]]; then REDIS_CONF=/etc/redis/redis.conf; fi
if [[ ! -f $REDIS_CONF ]]; then echo "no redis config"; exit 1; fi

# If redis also listen at 56379, stop it.
grep -q "^port 56379" $REDIS_CONF; STOP_REDIS=$?
systemctl status redis > /dev/null; REDIS_ALIVE=$?
if [[ $STOP_REDIS -eq 0 && $REDIS_ALIVE -eq 0 ]]; then
  systemctl stop redis; if [[ $? -ne 0 ]]; then echo "Stop redis failed"; exit 1; fi
fi

# Always write all cli tools to /root
# Note that it's not required tool, so we only need a place to save the script.
REDIS_CLI=/root/redis-cli
API_SECRET_CLI=/root/api-secret
echo "Setup redis script, REDIS_CONF=${REDIS_CONF}, REDIS_CLI=${REDIS_CLI}, API_SECRET_CLI=${API_SECRET_CLI}"

# Save host to .env
grep -q "^REDIS_HOST=" .env; REDIS_HOST=$?
if [[ $REDIS_HOST -ne 0 ]]; then
  echo "REDIS_HOST=redis" >> .env && echo "Setup REDIS_HOST=redis ok"
  if [[ $? -ne 0 ]]; then echo "Setup REDIS_HOST failed"; exit 1; fi
fi

# Save port to .env
grep -q "^REDIS_PORT=" .env; SETUP_PORT=$?
if [[ $SETUP_PORT -ne 0 ]]; then
  echo "REDIS_PORT=56379" >> .env && echo "Setup REDIS_PORT=56379 ok"
  if [[ $? -ne 0 ]]; then echo "Setup REDIS_PORT failed"; exit 1; fi
fi

# Save password to .env
grep -q "^REDIS_PASSWORD=" .env; SETUP_PASSWORD=$?
if [[ $SETUP_PASSWORD -ne 0 ]]; then
  REDIS_PASSWORD=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)
  echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env && echo "Setup REDIS_PASSWORD ok"
  if [[ $? -ne 0 ]]; then echo "Setup REDIS_PASSWORD failed"; exit 1; fi
fi

if [[ ! -z $REDIS_CLI ]]; then
  echo '#!/usr/bin/env bash' > $REDIS_CLI &&
  cat .env |grep REDIS >> $REDIS_CLI &&
  echo "redis-cli -p \$REDIS_PORT -a \$REDIS_PASSWORD \$*" >> $REDIS_CLI &&
  chmod +x $REDIS_CLI && echo "Create redis-cli helper at $REDIS_CLI"
fi

if [[ ! -z $API_SECRET_CLI ]]; then
  echo '#!/usr/bin/env bash' > $API_SECRET_CLI &&
  cat .env |grep REDIS >> $API_SECRET_CLI &&
  echo "redis-cli -p \$REDIS_PORT -a \$REDIS_PASSWORD \$* HGET SRS_PLATFORM_SECRET token" >> $API_SECRET_CLI &&
  chmod +x $API_SECRET_CLI && echo "Create api-secret helper at $API_SECRET_CLI"
fi

