#!/usr/bin/env bash

echo "Try to switch mgmt version"

# If no mgmt binary, create it from docker.
if [[ ! -f mgmt ]]; then
  # Prepare target version in version.go
  bash auto/prepare_next_version
  if [[ $? -ne 0 ]]; then echo "Prepare MGMT failed"; exit 1; fi
fi

# If already prepared, switch to next version.
if [[ -f mgmt.next ]]; then
  # Remove current version file.
  if [[ -f mgmt.current ]]; then
    echo "Remove current version $(readlink mgmt.current)"
    rm -f mgmt $(readlink mgmt.current 2>/dev/null)
  fi

  echo "Create current version $(readlink mgmt.next)"
  rm -f mgmt.current && ln -sf $(readlink mgmt.next) mgmt.current && rm -f mgmt.next
  rm -f mgmt && ln -sf $(readlink mgmt.current) mgmt
fi

echo "Switch to $(./mgmt -v) ok"

