#!/usr/bin/env bash

# Ignore darwin
if [[ $(uname -s) == 'Darwin' ]]; then
  echo "Directly finish upgrade for macOS development"
  exit 0;
fi

echo "UI is moved to platform, and upgrade by docker"

