#!/usr/bin/env bash

# Prepare the system, this could run again and again.
echo "Upgrade prepare script"

# Ignore darwin
if [[ ! -d /usr/local/srs-cloud && $(uname -s) == 'Darwin' ]]; then
  echo "Directly finish upgrade for macOS development"
  sleep 3; exit 0;
fi

# Initialize the REGION and SOURCE, try to load from param 1.
# Note that we MUST load the REGION and SOURCE again, because nodejs executes this directly, and the region list might
# changed after the image is created.
if [[ $REGION == '' ]]; then REGION=$1; fi
. auto/upgrade_region

# Update the sysctl
#   update_sysctl config value empty-line-prefix description
#   update_sysctl net.ipv4.ip_forward 1 0 "# Controls IP packet forwarding"
function update_sysctl() {
    SYSCTL_KEY=$1 && SYSCTL_VALUE=$2 && SYSCTL_EMPTY_LINE=$3 && SYSCTL_COMMENTS=$4
    echo "Update with sysctl $SYSCTL_KEY=$SYSCTL_VALUE, empty-line=$SYSCTL_EMPTY_LINE, comment=$SYSCTL_COMMENTS"

    grep -q "^${SYSCTL_KEY}[ ]*=" /etc/sysctl.conf
    if [[ $? == 0 ]]; then
      sed -i "s/^${SYSCTL_KEY}[ ]*=.*$/${SYSCTL_KEY} = ${SYSCTL_VALUE}/g" /etc/sysctl.conf
    else
      if [[ $SYSCTL_EMPTY_LINE == 1 ]]; then echo '' >> /etc/sysctl.conf; fi &&
      if [[ $SYSCTL_COMMENTS != '' ]]; then echo "$SYSCTL_COMMENTS" >> /etc/sysctl.conf; fi &&
      echo "${SYSCTL_KEY} = ${SYSCTL_VALUE}" >> /etc/sysctl.conf
    fi
    if [[ $? -ne 0 ]]; then echo "Failed to sysctl $SYSCTL_KEY = $SYSCTL_VALUE $SYSCTL_COMMENTS"; exit 1; fi

    RESULT=$(grep "^${SYSCTL_KEY}[ ]*=" /etc/sysctl.conf)
    echo "Update done: ${RESULT}"
}

# Setup the UDP kernel options before restart
# See https://www.jianshu.com/p/6d4a89359352
# TODO: FIXME: REMOVE-NEXT-RELEASE: Setup the kernel options by the image itself.
if [[ $(uname -s) != 'Darwin' ]]; then
  # 允许网络转发，Docker依赖这个配置
  # See https://stackoverflow.com/a/41453306/17679565
  update_sysctl net.ipv4.ip_forward 1 1 "# Controls IP packet forwarding"
  if [[ $? -ne 0 ]]; then echo "Setup the network forward failed"; exit 1; fi

  # Setup the UDP kernel buffer.
  # See https://www.jianshu.com/p/6d4a89359352
  update_sysctl net.core.rmem_max 16777216 1 "# For RTC/SRT over UDP"
  update_sysctl net.core.rmem_default 16777216
  update_sysctl net.core.wmem_max 16777216
  update_sysctl net.core.wmem_default 16777216
  if [[ $? -ne 0 ]]; then echo "Setup the UDP kernel options failed"; exit 1; fi
fi

# Setup the UDP kernel options for this session.
# See https://www.jianshu.com/p/6d4a89359352
if [[ $(uname -s) != 'Darwin' ]]; then
  sysctl net.core.rmem_max=16777216 &&
  sysctl net.core.rmem_default=16777216 &&
  sysctl net.core.wmem_max=16777216 &&
  sysctl net.core.wmem_default=16777216
  if [[ $? -ne 0 ]]; then echo "Setup the UDP kernel options failed"; exit 1; fi
fi

# Use different docker registry.
REGISTRY=registry.cn-hangzhou.aliyuncs.com
if [[ $SOURCE == GITHUB ]]; then REGISTRY=sgccr.ccs.tencentyun.com; fi
echo "Detect REGISTRY=$REGISTRY"

bash auto/upgrade_containers $REGISTRY
if [[ $? -ne 0 ]]; then echo "Update docker containers failed"; exit 1; fi

# Setup git alias to make it convenient.
echo "Setup git alias to make it more convenient" &&
git config --local alias.co checkout &&
git config --local alias.br branch &&
git config --local alias.ci commit &&
git config --local alias.st status
if [[ $? -ne 0 ]]; then echo "Setup git alias failed"; exit 1; fi

# Setup nginx configuration.
if [[ -d /etc/nginx/default.d ]]; then
  # Overwrite the default nginx config.
  cp containers/conf/nginx.conf /etc/nginx/nginx.conf && echo "Refresh nginx.conf ok"
  if [[ $? -ne 0 ]]; then echo "Refresh nginx.conf failed"; exit 1; fi

  # For DO Ubuntu20, use www-data as nginx user.
  if [[ $CLOUD == DO ]];  then
    echo "Switch to user www-data for nginx" &&
    sed -i "s/user nginx;/user www-data;/g" /etc/nginx/nginx.conf
    if [[ $? -ne 0 ]]; then echo "Setup nginx.conf failed"; exit 1; fi
  fi

  # For nginx default config.
  cp containers/conf/nginx.default.conf /etc/nginx/default.d/default.conf && echo "Refresh nginx default.conf ok"
  if [[ $? -ne 0 ]]; then echo "Refresh nginx default.conf failed"; exit 1; fi

  # For nginx mgmt config.
  cp containers/conf/nginx.mgmt.conf /etc/nginx/default.d/mgmt.conf && echo "Refresh nginx mgmt.conf ok"
  if [[ $? -ne 0 ]]; then echo "Refresh nginx mgmt.conf failed"; exit 1; fi

  # For nginx srs config.
  cp containers/conf/nginx.srs.conf /etc/nginx/default.d/srs.conf && echo "Refresh nginx srs.conf ok"
  if [[ $? -ne 0 ]]; then echo "Refresh nginx srs.conf failed"; exit 1; fi

  # For DVR preview, create nginx location.
  cp containers/conf/nginx.dvr.preview.conf /etc/nginx/default.d/dvr.preview.conf && echo "Refresh nginx dvr.preview.conf ok"
  if [[ $? -ne 0 ]]; then echo "Refresh nginx dvr.preview.conf failed"; exit 1; fi

  # Reload nginx service.
  systemctl reload nginx && echo "Reload nginx ok"
  if [[ $? -ne 0 ]]; then echo "Reload nginx failed"; exit 1; fi
fi

# Execute script for each run.
bash auto/foreach_run
if [[ $? -ne 0 ]]; then echo "Execute for each run script failed"; exit 1; fi

