#!/usr/bin/env bash

echo "Update containers script."

REGISTRY=$1
if [[ $REGISTRY == '' ]]; then echo "No docker registry"; exit 1; fi

echo "Update the docker containers."
docker pull ${REGISTRY}/ossrs/node:slim &&
docker pull ${REGISTRY}/ossrs/prometheus &&
docker pull ${REGISTRY}/ossrs/redis_exporter &&
docker pull ${REGISTRY}/ossrs/node-exporter &&
docker pull ${REGISTRY}/ossrs/certbot &&
docker pull ${REGISTRY}/ossrs/srs:node-av
if [[ $? -ne 0 ]]; then echo "Update the containers failed"; exit 1; fi

# Remove the containers if need upgrade
#   update_containers registry image
#   update_containers ccr.ccs.tencentyun.com ossrs/lighthouse:4
#   update_containers registry.cn-hangzhou.aliyuncs.com ossrs/lighthouse:4
function update_containers() {
  REGISTRY=$1 && IMAGE=$2
  echo "Update containers for REGISTRY=$REGISTRY IMAGE=$IMAGE"

  # We must store the container images ID before pull, which will change it.
  IMAGE_IDS=$(docker ps -a | grep $IMAGE | awk '{print $1}')
  echo "The containers for $REGISTRY/$IMAGE is $IMAGE_IDS"

  docker pull $REGISTRY/$IMAGE
  if [[ $? -ne 0 ]]; then echo "Update the image $REGISTRY/$IMAGE failed"; exit 1; fi

  for IMAGE_ID in $IMAGE_IDS; do
    LATEST=$(docker inspect --format "{{.Id}}" $REGISTRY/$IMAGE)
    RUNNING=$(docker inspect --format "{{.Image}}" $IMAGE_ID)
    NAME=$(docker inspect --format '{{.Name}}' $IMAGE_ID |sed 's|/||g')
    echo "Check $NAME RUNNING=$RUNNING, LATEST=$LATEST"

    if [[ $RUNNING != $LATEST ]]; then
      echo "Upgrade container $NAME from $RUNNING to $LATEST"
      docker rm -f $NAME
    fi
  done
}

# Update the containers before restart. Note that the containers are normally started by previous mgmt, with the
# upgraded image. So we only upgrade the images for all containers, and it's the responsibility for mgmt to restart the
# container if need to change the startup arguments.
echo "Upgrading all containers by images" &&
update_containers $REGISTRY ossrs/srs:4 &&
update_containers $REGISTRY ossrs/srs:5 &&
update_containers $REGISTRY ossrs/lighthouse:4 &&
update_containers $REGISTRY ossrs/lighthouse:5 &&
update_containers $REGISTRY ossrs/srs-terraform:hooks-1 &&
update_containers $REGISTRY ossrs/srs-terraform:tencent-1 &&
update_containers $REGISTRY ossrs/srs-terraform:ffmpeg-1 &&
# Note that we should update the platform image, so we could fast startup the container, because mgmt use another tag
# which has the same hash.
update_containers $REGISTRY ossrs/srs-terraform:platform-1
if [[ $? -ne 0 ]]; then echo "Upgrade containers failed"; exit 1; fi

# Removed unreferenced image, the TAG is <none>
for image in $(docker images |grep '<none>' |awk '{print $3}'); do
  docker rmi -f $image
  echo "Remove image $image, r0=$?"
done

