FROM registry.cn-hangzhou.aliyuncs.com/ossrs/srs:node-av

# Cache nodejs packages.
RUN npm i -g fs uuid jest moment dotenv koa koa-bodyparser koa-router koa-static koa2-cors \
  axios ioredis jsonwebtoken koa-mount koa-static-cache semver \
  cos-nodejs-sdk-v5 tencentcloud-sdk-nodejs

